sudo: required
dist: trusty
git:
  submodules: true
language: c
compiler: gcc
before_install:
  - echo "deb https://dl.bintray.com/rwth-os/hermitcore vivid main" | sudo tee -a /etc/apt/sources.list
  - travis_retry sudo apt-get -qq update
  - travis_retry sudo apt-get install -y curl wget qemu-system-x86 nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev flex bison packaging-dev rpm
  - travis_retry sudo apt-get install -y --force-yes binutils-hermit libhermit newlib-hermit pthread-embedded-hermit gcc-hermit
  - git submodule update --init lwip usr/libomp

script:
  - source cmake/local-cmake.sh
  - mkdir build
  - cd build
  - cmake ..
  - make -j1 package
  - cd $TRAVIS_BUILD_DIR
  - ./tests.sh

notifications:
  slack: hermitcore:UtcfeEXkbpx3WyIDK2Wm2beS
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=rwth-os/hermitcore
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - cd docker
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

deploy:
  on: master
  provider: bintray
  file: .bintray_descriptor.json
  user:
    secure: wo0yLY7xhGZYDqdB05UE+IOXXgYhAwj+zvtZh3ET2253hy35y74cDKMBNGfynH0aauPk8EFmN/LJoYaV/T9QF6pc1bilbqSg1/LJuL7hjAVVFaBSjwlE/Wbbb+EHNX5CR3qmC42SUvbrU+0WNvRu7WJBpZIoH9EtPv2Cj7uRV9+7Mtp/O3Ykl3E5LgkF5iA6Lo03TN+bZ1Vog5MbuJagDTpNa18vJ3jVYaed5gqOkghYYDpc5U9yxN3debS7/8MCl3u9V9uanMAyjc6wtbvJLotVkUwdXK8u9FohuWQ4pTEQ/QspLDDBuxaS3kLNWtzBMNQn6rcYIOWWKyD3uqvIhqjcErX7WChf3oGS1XPFfTHebNrHyV4KGvzkMAJUR/1qC5f4nZCsvgPv/35d702nky3Di2/WZsjD5zUR9g3+vPO8mnM3z8eA6ShVJcxezZ73Co3p0ZnBaF3J438bAKiT4nlrbIVpRzZzo/5nYTx//SefXSAmYCILr/y7xTYBqjfjMQHQZEMZSvJYRPbtP7eVCfWGEa2tG4rQndegUtwS+n1r8atcESL9eeUUM6sa1QzZYDYVseOc9GWcB7SIJzPOm8QTuTlkISHMGJ8FY+KHorP15VkVlr0EZ5c7KY0cBIbWoZGNQTg9+nSgChyf7ElNbAxPiCZsR0zafjMDhfcnzco=
  key:
    secure: JfsqEUO3Z60yGfuK5RSzwMoWZtaYflZtW7QE6R1DVMPEQ+CytzEdV2JaTpY14xz4yz1YpBBuQ0P3Q3e2rf/ORp8N8j7/5m3gfiDi8bRH3gX10r6vCQaUBilj0pz3amWUacxwBUEYR/f1029OnJ1qug30f4ARk7DWyuAePt0OboDXZ3j4JOi8xfXKTzofyKGugU4EuzhmKAbpHaBoX97g8z+gETC+wsBEYio8iD2h0ZOe/qZ0S+JGYkphIKcxpQazKdi3YrmWm0BUZsQRtkgoH7KUZm8vqfOUyVOrK+UGOTz4vXqCWHZ+wG1QRrGPUv8ehLrB26y2o02mmaDWQhM+I3RtllL06JDvDw40xjRImYtzg6xr7Mvl0OTQHprXrkN8gw2IbIivV8v31O46Ov+KIaN3CCx1IncnllBWjEXAIs4zPtvNj2Ad338JTkI/opHmPG0DI0DKE36r8wPZYTs/pHVpc3xEzwKYDklJkICjMLUakUGKppS7eKzKGRMjWvbT0vM/U7hHUcz0lA+BUoXedNmJQ1wBT85Ud8uobuKS4C8QmlgIuF1PI2+6LJr5LsCGZRvg7Pl1SPc3ZQLPHX4ggoLAnZZJiV/0ZPCn7XCLiUS1qws37l0uZT1zJQMFLsw9MGuP58tpT7WDuYYAwma/pL+OKC/JKoDhuJwM1I7wB4s=
env:
  global:
  - secure: FsBUz9OyI9zwrEcbK194jMOPYuGeIpVBQ35nlNP97sy/Eb81V5WXGD1qzGwqwgkWUJowEBTMGKrGZsmd1wYE2O/b+5louAy4eptN96bV6cqfbYvB5A37VBN/Uw6r0BETn9+bkbdZwAEei74NVquSJ1iclZEryc/Z/0zFW4lTmjH3eaJhqVeWCCoA3e0L1vK931SdNVg2pFFIJepi6UuLP/6/+fvTE+B6MMlsk2JD3dtf3sMkANcQy6ZbL59fhFfHA6lb7xK9wGDHnMNWr8QJeIdtW/Jq9ddc7TSqSnwCGnYMiaKsynNZbBrGuH1TlnZEMt4TGukR/ygzK7MJpLlps37uWnVkOHR9nbMOrXTrdXPfsTHzvOjx/0+cS2J2vkpqiTHBVC4ioCyqBCGJcy4uXE0tzNwXBSbzPJaktDYHuJ0XYPyoxpT3beWz7wFQKZPmd3FXV3D5RaAHu/wTRPGdirUynYdc2ZkeP7hniBBmyQVx7GVDMC74dUl2/wE4DmSuXHSGxEKqxaVwpebcY1xwGXWl1w9+q54BsledMzMN0a7B1AvqayuTXHeeqTQ//fLitkUUDMx3N/IcUKdQj0/iEDm5E1qTiaCk3OwBfh/brid39CFqBGCfTyJem1BXSLvi0cgf80bHVxlV8gMJ/B8b9bO1ok6afhCCSxW3Qg2pwRs=
  - secure: onKzPvzG8xV9LBO5mxCLd3gy2O32vK+7Hkwvfotb6g/Nmn9Sk91sppax4PgdxZ9M6gvM+2yccm0yNaJNfl6nedOARojRV26f0AkEb9aKdMjaQN8oRhUK4bF6qOdC5O/PsB6nnAI2+MAMsSlFdFM3SoQWFTL6mSg36r1GXP1HFRYe+aFxFaq9gixOKJbQ9UO0EN+k3KvOuVe2AAit0l1cqiOeYyFX3fe1ZlyStMYH1CZI2RQPwbzlh3vWbTEzEmtmOl77Jt6yXY1zcxk7tPA0zukOjcn6viSpuNYkYrN0nb+KBYe+nm0h07ORVzMDq76qAj34UPb+zpKPiaXcLSFTzq6CjWuzHhcpP56ycORgrr54eoJsNuPFpByKQU+MOgG8AyKPDqoU4JfeXFozZ/o1kLDl7xe7o+v0wXyWBhwxrlH2d3GP2j7oG9t8tRR0Oi+yzcgw4qn9OV2HMHyHLXKUSbSS2USPlyo+jCMQt9n/wZ3YLTd0O/0wtthtDxraWLSQYMaNzFzkMHTdgGb/aGrgYqeCehhUuRH1fgZ7dpFVyr0ld+9WGOM89Z+QLbJ3wKthTbpredZJHFDSUdeDHN9NMdrRluNQiaTv2mG5n0ROvPlSSa3pNsxjjvgVjDrTwgHlWVhvm13rA0zofq3AN3JI23LZuuR7EKEhW1PtpX4OuqI=
  - secure: zG3MYXlVn+kv6EvxjnMY9oosMnG6RjVXpiAe3SHcqBrcFwnJBIJGXrgfXDJVymOM7DPsCI37ifwVG6DSOpdz6CuK8GaFvc5LjzgwJjcltF5c0nVarPPeShevBXFuowX5zqPmZ3O6qG56ik/iOFiipCEnhXEt6SzsjMabbqhkDM4EDztjfxEgUvQLYhgxIydHDlYvrnipD3d3IehKImXQIfuhX3BlXN73YnWY6LmOcTDaRDZcUa5dHbqDFm/kuOSqztB9J/0S8EqrCeBKXVHYCe1mvO+x3EYXv7x5RCI3lX7Miz8pMPe35KPuqCpXK/wKTYVDAeNGuUKHuySGkc7fzkEJHo6BKAk/jhQZ8VZTt0+yl0iQqvtPBKUOZbRUn/pj+x0ocUParzuhdYuxtE8VqubxU7Xr0/gjB3N+XBrKNQCUoyS8KvH2dp24UGPTdeszLTTDtIlhmWvEkUcnZk3ykTtyZwzU/sEoaHvLK3/AdS/oQvJr2/8wDyJnjokMIVQZx0xni+B5/g9jEuahWKPCbG0eZL8k+5dDjiB+BYvta6Do37MoMyx1jmdfovKqF8IP6u7ihlxrO8dn24SCWuO4KyUj3L96USGBq/uo5Apq1Bbv3qM3OFfzYrA7npLec/jsmuaCBqbIJ2SGAVU15tc2+GG/Zzf1DqhQVJGbroqA2UQ=
  - COMMIT=${TRAVIS_COMMIT::8}
