sudo: required
git:
  depth: 3
  submodules: true
env:
  matrix:
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash
  -c "cd /work; ./tests.sh ${OS_TYPE} ${OS_NAME}"
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- dpkg-deb -b tmp libhermit-0.3.0-all.deb
deploy:
  provider: bintray
  on:
    branch: master
  skip_cleanup: true
  file: ".bintray_descriptor.json"
