[package]
name = "hermit-rs"
version = "0.2.0"
authors = [
        "Stefan Lankes <slankes@eonerc.rwth-aachen.de>",
]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"	# Low-level functions like memcpy.
spin = "0.4.5"		# Spinlocks.
x86 = "0.8.1"		# CPU data structures.
