[package]
name = "hermit-loader"
version = "0.2.0"
authors = ["Colin Finck <colin.finck@rwth-aachen.de>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.3"

[target.'cfg(target_arch = "aarch64")'.dependencies.byteorder]
version = "1.2.4"
default-features = false

[target.'cfg(target_arch = "aarch64")'.dependencies.hermit-dtb]
path = "../crates/hermit-dtb"

[target.'cfg(target_arch = "x86_64")'.dependencies.hermit-multiboot]
path = "../crates/hermit-multiboot"

[dependencies.lazy_static]
version = "1.0.1"
features = ["spin_no_std"]

[dependencies.rlibc]
path = "../crates/rlibc"    # Low-level functions like memcpy.
features = ["nightly"]

[target.'cfg(target_arch = "x86_64")'.dependencies.x86]
version = "0.9.0"
default-features = false

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
