[package]
name = "hermit-loader"
version = "0.1.0"
authors = [
        "Colin Finck <colin.finck@rwth-aachen.de>",
]

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.0"
multiboot = "0.3.0"

[dependencies.rlibc]
path = "../crates/rlibc"    # Low-level functions like memcpy.
features = ["nightly"]

[dependencies.x86]
path = "../librs/crates/x86"
default-features = false

# The development profile, used for `cargo build`.
[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-C debuginfo`
                   # a value of `true` is equivalent to `2`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
