[package]
name = "hermit-loader"
version = "0.1.0"
authors = ["Colin Finck <colin.finck@rwth-aachen.de>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.1"

[dependencies.hermit-multiboot]
path = "../crates/hermit-multiboot"

[dependencies.rlibc]
path = "../crates/rlibc"    # Low-level functions like memcpy.
features = ["nightly"]

[dependencies.x86]
path = "../crates/x86"
default-features = false

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
