name: Benchmark

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
          pull-requests: write 

env:
  GH_TOKEN: ${{ github.token }}

jobs:
    benchmark:
        name: Run Benchmarks
        runs-on: ubuntu-latest #[self-hosted]
        environment: ${{ github.event_name == 'push' && 'benchmark' || '' }}

        strategy:
          matrix:
            include:
              #- benchmark-file: /kernel/.github/benchmarks/general.yaml
              #  benchmark-matrix-name: General
              #- benchmark-file: /kernel/.github/benchmarks/misc.yaml
              #  benchmark-matrix-name: Misc
              - benchmark-file: /kernel/.github/benchmarks/netbench.yaml
                benchmark-matrix-name: Netbench

        steps:
          - name: Checkout hermit-rs
            uses: actions/checkout@v4
            with:
              repository: hermit-os/hermit-rs
              submodules: true
          - name: Remove hermit-kernel submodule
            run: git rm -r kernel
          - name: Checkout hermit-kernel
            uses: actions/checkout@v4
            with:
              path: kernel
          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends qemu-system-x86 cpu-checker parallel gh
          - name: Download loader
            run: gh release download --repo hermit-os/loader --pattern hermit-loader-x86_64
          - uses: mkroening/rust-toolchain-toml@main
          - name: Install uhyve
            run: cargo +stable install --locked uhyve
          - name: Check KVM availability
            run: |
              lscpu
              kvm-ok
          - uses: dtolnay/rust-toolchain@stable
          - uses: dtolnay/rust-toolchain@nightly
            with:
              components: rust-src
          - uses: mkroening/rust-toolchain-toml@main
          - run: rustup component add llvm-tools
            working-directory: .
          - run: rustup target add wasm32-wasip1
            working-directory: .
          - uses: mkroening/rust-toolchain-toml@main
            with:
              toolchain-file: "kernel/rust-toolchain.toml"
          - name: manual run
            run: |
              cargo build --manifest-path benches/netbench/Cargo.toml --bin tcp-client-bw \
                -Zbuild-std=core,alloc,std,panic_abort \
                --target x86_64-unknown-hermit \
                --release
              cargo build --manifest-path benches/netbench/Cargo.toml --bin tcp-server-bw --release --target x86_64-unknown-linux-gnu
              cargo run --manifest-path benches/netbench/Cargo.toml \
                --bin tcp-server-bw \
                --target x86_64-unknown-linux-gnu \
                --release \
                -- --address 10.0.5.5 --bytes 1048576 --rounds 1000 &
              sleep 2 && sudo qemu-system-x86_64 \
                -display none \
                -smp 2 \
                -m 1024M \
                -serial stdio \
                -enable-kvm \
                -cpu host,migratable=no,+invtsc \
                -kernel hermit-loader-x86_64 \
                -initrd target/x86_64-unknown-hermit/release/tcp-client-bw \
                -netdev tap,id=net0,ifname=tap10,script=xtask/hermit-ifup,vhost=on \
                -device virtio-net-pci,netdev=net0,disable-legacy=on \
                -append "-- --address 10.0.5.1 --bytes 1048576 --rounds 1000"
          - name: Run benchmarks
            uses: hermit-os/hermit-bench@main
            id: run-bench
            with: 
              benchmark-file: ${{ matrix.benchmark-file }}
          - name: Store benchmark results
            uses: hermit-os/github-action-benchmark@main
            with:
              tool: 'hermit-bench'
              output-file-path: ${{ steps.run-bench.outputs.result-file }}
              github-token: ${{ github.event_name == 'push' && secrets.HERMIT_BENCH_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
              benchmark-data-dir-path: benchmarks
              gh-repository: github.com/CarlWachter/hermit-bench
              comment-always: true
              benchmark-matrix-name: ${{ matrix.benchmark-matrix-name }}
              auto-push: ${{ github.event_name == 'push' }} 