name: Clippy

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hermitcore/toolchain@downstream
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
