name: Doc

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install nasm
      - uses: actions/checkout@v3
      - name: Rustup (apply rust-toolchain.toml)
        run: rustup show
      - run: rustup target add aarch64-unknown-none-softfloat
      - name: Doc
        env:
          RUSTDOCFLAGS: -D warnings
        run: |
          cargo doc --package libhermit-rs --no-deps --document-private-items --target x86_64-unknown-none
          cargo doc --package libhermit-rs --no-deps --document-private-items --target aarch64-unknown-none-softfloat
