name: Publish Benchmarks

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

jobs:
  publish_benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'benchmark' || '' }}

    permissions:
      pull-requests: write

    strategy:
      matrix:
        include:
          - benchmark-file: kernel/.github/benchmarks/general.yaml
            benchmark-matrix-name: General
          - benchmark-file: kernel/.github/benchmarks/misc.yaml
            benchmark-matrix-name: Misc

    steps:
    - name: 'Download results.json artifact'
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Get artifacts
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });

          // print the artifacts for debugging
          console.log("Artifacts:", artifacts.data.artifacts);

          // Find the artifact named 'results'
          const artifact = artifacts.data.artifacts.find(a => a.name === '${{ matrix.benchmark-matrix-name }}-benchmark-results');
          if (!artifact) {
            throw new Error("Artifact '${{ matrix.benchmark-matrix-name }}-benchmark-results' not found.");
          }

          // Download the artifact as a zip
          const download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: artifact.id,
            archive_format: 'zip',
          });

          // Save ZIP to disk
          const zipPath = path.join(process.env.GITHUB_WORKSPACE, 'results.zip');
          fs.writeFileSync(zipPath, Buffer.from(download.data));
    - name: 'Unzip artifact'
      run: unzip results.zip
    - name: Store benchmark results
      uses: hermit-os/github-action-benchmark@main
      with:
        tool: "hermit-bench"
        output-file-path: results.json
        github-token: ${{ github.event_name == 'push' && secrets.HERMIT_BENCH_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        benchmark-data-dir-path: .
        gh-repository: github.com/CarlWachter/hermit-bench
        comment-always: true
        benchmark-matrix-name: ${{ matrix.benchmark-matrix-name }}
        auto-push: ${{ github.event_name == 'push' }}