name: Publish Benchmarks

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

jobs:
  publish_benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'benchmark' || '' }}

    permissions:
      pull-requests: write
      actions: read
      contents: read

    strategy:
      matrix:
        include:
          - benchmark-file: kernel/.github/benchmarks/general.yaml
            benchmark-matrix-name: General
          - benchmark-file: kernel/.github/benchmarks/misc.yaml
            benchmark-matrix-name: Misc

    steps:
    - name: Download results artifact
      uses: actions/download-artifact@v4
      with:
        name: '${{ matrix.benchmark-matrix-name }}-benchmark-results'
        path: ./artifact
    - name: Store benchmark results
      uses: hermit-os/github-action-benchmark@main
      with:
        tool: "hermit-bench"
        output-file-path: ./artifact/results.json
        github-token: ${{ github.event_name == 'push' && secrets.HERMIT_BENCH_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        benchmark-data-dir-path: .
        gh-repository: github.com/CarlWachter/hermit-bench
        comment-always: true
        benchmark-matrix-name: ${{ matrix.benchmark-matrix-name }}
        auto-push: ${{ github.event_name == 'push' }}